### ISSUE TITLE
Regression: 3.4.4 fails to build on macOS 10.6: `syscall.c: error: too few arguments to function ‘do_lchown’`

### ISSUE THREAD

**Issue by barracuda156** [WayneD/rsync#1025]
```
:notice:configure --->  Configuring rsync
:debug:configure gcc_compilers.tcl not found in ports tree, using built-in selections
:debug:configure Preferred compilers: gcc-4.2 llvm-gcc-4.2 gcc-4.0 macports-gcc-16 macports-gcc-14 macports-gcc-13 macports-gcc-12 macports-gcc-11 macports-gcc-10 macports-gcc-9 macports-gcc-8 macports-gcc-7 macports-gcc-6 macports-gcc-5
:debug:configure Using compiler 'Xcode GCC 4.2'
:debug:configure elevating privileges for configure ccache: euid changed to 0, egid changed to 0.
:debug:configure dropping privileges: euid changed to 503, egid changed to 501.
:warn:configure ccache_dir /opt/local/var/macports/build/.ccache could not be initialized; disabling ccache: couldn't execute "ccache": no such file or directory
:debug:configure Executing proc-pre-org.macports.configure-configure-0
:debug:configure system -W /opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4: ./prepare-source
:info:configure make: Nothing to be done for `conf'.
:debug:configure Executing org.macports.configure (rsync)
:debug:configure Environment: 
:debug:configure CC='/usr/bin/gcc-4.2'
:debug:configure CC_PRINT_OPTIONS='YES'
:debug:configure CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/rsync-62cd6a74/work/.CC_PRINT_OPTIONS'
:debug:configure CFLAGS='-pipe -Os -arch ppc'
:debug:configure CPATH='/opt/local/include'
:debug:configure CPPFLAGS='-I/opt/local/include'
:debug:configure CXX='/usr/bin/g++-4.2'
:debug:configure CXXFLAGS='-pipe -Os -arch ppc'
:debug:configure DEVELOPER_DIR='/Developer'
:debug:configure F90FLAGS='-pipe -Os -m32'
:debug:configure FCFLAGS='-pipe -Os -m32'
:debug:configure FFLAGS='-pipe -Os -m32'
:debug:configure INSTALL='/usr/bin/install -c'
:debug:configure LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc'
:debug:configure LIBRARY_PATH='/opt/local/lib'
:debug:configure MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:configure OBJC='/usr/bin/gcc-4.2'
:debug:configure OBJCFLAGS='-pipe -Os -arch ppc'
:debug:configure OBJCXX='/usr/bin/g++-4.2'
:debug:configure OBJCXXFLAGS='-pipe -Os -arch ppc'
:debug:configure SOURCE_DATE_EPOCH='1783820719'
:info:configure Executing:  cd "/opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4" && ./configure --prefix=/opt/local --with-rsyncd-conf=/opt/local/etc/rsyncd.conf 
:debug:configure system:  cd "/opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4" && ./configure --prefix=/opt/local --with-rsyncd-conf=/opt/local/etc/rsyncd.conf 
:info:configure checking for gcc... /usr/bin/gcc-4.2
:info:configure checking whether the C compiler works... yes
:info:configure checking for C compiler default output file name... a.out
:info:configure checking for suffix of executables... 
:info:configure checking whether we are cross compiling... no
:info:configure checking for suffix of object files... o
:info:configure checking whether the compiler supports GNU C... yes
:info:configure checking whether /usr/bin/gcc-4.2 accepts -g... yes
:info:configure checking for /usr/bin/gcc-4.2 option to enable C11 features... unsupported
:info:configure checking for /usr/bin/gcc-4.2 option to enable C99 features... -std=gnu99
:info:configure checking for stdio.h... yes
:info:configure checking for stdlib.h... yes
:info:configure checking for string.h... yes
:info:configure checking for inttypes.h... yes
:info:configure checking for stdint.h... yes
:info:configure checking for strings.h... yes
:info:configure checking for sys/stat.h... yes
:info:configure checking for sys/types.h... yes
:info:configure checking for unistd.h... yes
:info:configure checking for utime.h... yes
:info:configure checking whether byte ordering is bigendian... yes
:info:configure checking for dirent.h that defines DIR... yes
:info:configure checking for library containing opendir... none required
:info:configure checking for sys/wait.h that is POSIX.1 compatible... yes
:info:configure checking for sys/fcntl.h... yes
:info:configure checking for sys/select.h... yes
:info:configure checking for fcntl.h... yes
:info:configure checking for sys/time.h... yes
:info:configure checking for sys/unistd.h... yes
:info:configure checking for unistd.h... (cached) yes
:info:configure checking for utime.h... (cached) yes
:info:configure checking for compat.h... no
:info:configure checking for sys/param.h... yes
:info:configure checking for ctype.h... yes
:info:configure checking for sys/wait.h... (cached) yes
:info:configure checking for sys/stat.h... (cached) yes
:info:configure checking for sys/ioctl.h... yes
:info:configure checking for sys/filio.h... yes
:info:configure checking for string.h... (cached) yes
:info:configure checking for stdlib.h... (cached) yes
:info:configure checking for sys/socket.h... yes
:info:configure checking for sys/mode.h... no
:info:configure checking for grp.h... yes
:info:configure checking for sys/un.h... yes
:info:configure checking for sys/attr.h... yes
:info:configure checking for arpa/inet.h... yes
:info:configure checking for arpa/nameser.h... yes
:info:configure checking for locale.h... yes
:info:configure checking for sys/types.h... (cached) yes
:info:configure checking for netdb.h... yes
:info:configure checking for malloc.h... no
:info:configure checking for float.h... yes
:info:configure checking for limits.h... yes
:info:configure checking for iconv.h... yes
:info:configure checking for libcharset.h... yes
:info:configure checking for langinfo.h... yes
:info:configure checking for mcheck.h... no
:info:configure checking for sys/acl.h... yes
:info:configure checking for acl/libacl.h... no
:info:configure checking for attr/xattr.h... no
:info:configure checking for sys/xattr.h... yes
:info:configure checking for sys/extattr.h... no
:info:configure checking for dl.h... no
:info:configure checking for popt.h... yes
:info:configure checking for popt/popt.h... no
:info:configure checking for linux/falloc.h... no
:info:configure checking for netinet/in_systm.h... yes
:info:configure checking for netgroup.h... no
:info:configure checking for zlib.h... yes
:info:configure checking for xxhash.h... yes
:info:configure checking for openssl/md4.h... yes
:info:configure checking for openssl/md5.h... yes
:info:configure checking for zstd.h... yes
:info:configure checking for lz4.h... yes
:info:configure checking for sys/file.h... yes
:info:configure checking for bsd/string.h... no
:info:configure checking for netinet/ip.h... yes
:info:configure checking whether sys/types.h defines makedev... yes
:info:configure configure.sh: Configuring rsync 3.4.4
:info:configure checking build system type... powerpc-apple-darwin10.8.0
:info:configure checking host system type... powerpc-apple-darwin10.8.0
:info:configure checking whether to include debugging symbols... yes
:info:configure checking for gcc... (cached) /usr/bin/gcc-4.2
:info:configure checking whether the compiler supports GNU C... (cached) yes
:info:configure checking whether /usr/bin/gcc-4.2 accepts -g... (cached) yes
:info:configure checking for /usr/bin/gcc-4.2 option to enable C11 features... (cached) unsupported
:info:configure checking for /usr/bin/gcc-4.2 option to enable C99 features... (cached) -std=gnu99
:info:configure checking how to run the C preprocessor... /usr/bin/gcc-4.2 -std=gnu99 -E
:info:configure checking whether the compiler supports GNU C++... yes
:info:configure checking whether /usr/bin/g++-4.2 accepts -g... yes
:info:configure checking for /usr/bin/g++-4.2 option to enable C++11 features... unsupported
:info:configure checking for /usr/bin/g++-4.2 option to enable C++98 features... unsupported
:info:configure checking for gawk... no
:info:configure checking for mawk... no
:info:configure checking for nawk... no
:info:configure checking for awk... awk
:info:configure checking for grep that handles long lines and -e... /usr/bin/grep
:info:configure checking for egrep... /usr/bin/grep -E
:info:configure checking for a BSD-compatible install... /usr/bin/install -c
:info:configure checking for a race-free mkdir -p... mkdir -p
:info:configure checking for perl... /usr/bin/perl
:info:configure checking for python3... no
:info:configure checking if md2man can create manpages... no - python3 not found
:info:configure checking if we require man-page building... optional
:info:configure checking for remsh... 0
:info:configure checking for sh... /bin/sh
:info:configure checking for fakeroot... /usr/bin/fakeroot
:info:configure checking the group for user "nobody"... nobody
:info:configure checking whether to enable rolling-checksum SIMD optimizations... no
:info:configure checking if assembler accepts noexecstack... no
:info:configure checking for openat2... no
:info:configure checking for broken largefile support... no
:info:configure checking for -I/opt/local/include option for large files... none needed
:info:configure checking whether to enable ipv6... yes
:info:configure checking whether to call shutdown on all sockets... no
:info:configure checking whether to use included zlib... ./zlib
:info:configure checking whether to enable use of openssl crypto library... yes
:info:configure checking for library containing EVP_MD_CTX_copy... -lcrypto
:info:configure checking whether to enable MD5 ASM optimizations... no
:info:configure checking whether to enable rolling-checksum ASM optimizations... no
:info:configure checking whether to enable xxhash checksum support... yes
:info:configure checking for library containing XXH64_createState... -lxxhash
:info:configure checking whether to enable zstd compression... yes
:info:configure checking for library containing ZSTD_minCLevel... -lzstd
:info:configure checking whether to enable LZ4 compression... yes
:info:configure checking for library containing LZ4_compress_default... -llz4
:info:configure checking if makedev takes 3 args... no
:info:configure checking size of int... 4
:info:configure checking size of long... 4
:info:configure checking size of long long... 8
:info:configure checking size of short... 2
:info:configure checking size of int16_t... 2
:info:configure checking size of uint16_t... 2
:info:configure checking size of int32_t... 4
:info:configure checking size of uint32_t... 4
:info:configure checking size of int64_t... 8
:info:configure checking size of off_t... 8
:info:configure checking size of off64_t... 0
:info:configure checking size of time_t... 4
:info:configure checking size of char*... 4
:info:configure checking for inline... inline
:info:configure checking for long double with more range or precision than double... yes
:info:configure checking for uid_t... yes
:info:configure checking for gid_t... yes
:info:configure checking for mode_t... yes
:info:configure checking for off_t... yes
:info:configure checking for size_t... yes
:info:configure checking for pid_t... yes
:info:configure checking for id_t... yes
:info:configure checking type of array argument to getgroups... gid_t
:info:configure checking for struct stat.st_rdev... yes
:info:configure checking for struct stat.st_mtimensec... no
:info:configure checking for struct stat.st_mtimespec.tv_nsec... yes
:info:configure checking for struct stat.st_mtim.tv_nsec... no
:info:configure checking for socklen_t... yes
:info:configure checking for errno in errno.h... yes
:info:configure checking for connect... yes
:info:configure checking for library containing inet_ntop... none required
:info:configure checking for library containing iconv_open... no
:info:configure checking for library containing libiconv_open... -liconv
:info:configure checking for iconv declaration... 
:info:configure          extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
:info:configure checking for inet_ntop... yes
:info:configure checking for inet_pton... yes
:info:configure checking for struct addrinfo... yes
:info:configure checking for struct sockaddr_storage... yes
:info:configure checking for egrep -e... (cached) /usr/bin/grep -E
:info:configure checking whether defines needed by getaddrinfo exist... yes
:info:configure checking for getaddrinfo... yes
:info:configure checking for struct sockaddr.sa_len... yes
:info:configure checking for struct sockaddr_in.sin_len... yes
:info:configure checking for struct sockaddr_un.sun_len... no
:info:configure checking for struct sockaddr_in6.sin6_scope_id... yes
:info:configure checking for struct stat64... yes
:info:configure checking for strcasecmp... yes
:info:configure checking for aclsort... no
:info:configure checking for aclsort in -lsec... no
:info:configure checking whether utime accepts a null argument... yes
:info:configure checking for size_t... (cached) yes
:info:configure checking for working alloca.h... yes
:info:configure checking for alloca... yes
:info:configure checking for waitpid... yes
:info:configure checking for wait4... yes
:info:configure checking for getcwd... yes
:info:configure checking for chown... yes
:info:configure checking for chmod... yes
:info:configure checking for lchmod... yes
:info:configure checking for mknod... yes
:info:configure checking for mkfifo... yes
:info:configure checking for fchmod... yes
:info:configure checking for fstat... yes
:info:configure checking for ftruncate... yes
:info:configure checking for strchr... yes
:info:configure checking for readlink... yes
:info:configure checking for link... yes
:info:configure checking for utime... yes
:info:configure checking for utimes... yes
:info:configure checking for lutimes... yes
:info:configure checking for strftime... yes
:info:configure checking for chflags... yes
:info:configure checking for getattrlist... yes
:info:configure checking for mktime... yes
:info:configure checking for innetgr... yes
:info:configure checking for linkat... no
:info:configure checking for mknodat... no
:info:configure checking for mkfifoat... no
:info:configure checking for memmove... yes
:info:configure checking for lchown... yes
:info:configure checking for vsnprintf... yes
:info:configure checking for snprintf... yes
:info:configure checking for vasprintf... yes
:info:configure checking for asprintf... yes
:info:configure checking for setsid... yes
:info:configure checking for strpbrk... yes
:info:configure checking for strlcat... yes
:info:configure checking for strlcpy... yes
:info:configure checking for stpcpy... yes
:info:configure checking for strtol... yes
:info:configure checking for mallinfo... no
:info:configure checking for mallinfo2... no
:info:configure checking for getgroups... yes
:info:configure checking for setgroups... yes
:info:configure checking for geteuid... yes
:info:configure checking for getegid... yes
:info:configure checking for setlocale... yes
:info:configure checking for setmode... yes
:info:configure checking for open64... no
:info:configure checking for lseek64... no
:info:configure checking for mkstemp64... no
:info:configure checking for mtrace... no
:info:configure checking for va_copy... no
:info:configure checking for __va_copy... no
:info:configure checking for seteuid... yes
:info:configure checking for strerror... yes
:info:configure checking for putenv... yes
:info:configure checking for iconv_open... no
:info:configure checking for locale_charset... yes
:info:configure checking for nl_langinfo... yes
:info:configure checking for getxattr... yes
:info:configure checking for extattr_get_link... no
:info:configure checking for sigaction... yes
:info:configure checking for sigprocmask... yes
:info:configure checking for setattrlist... yes
:info:configure checking for getgrouplist... yes
:info:configure checking for initgroups... yes
:info:configure checking for utimensat... no
:info:configure checking for posix_fallocate... no
:info:configure checking for attropen... no
:info:configure checking for setvbuf... yes
:info:configure checking for nanosleep... yes
:info:configure checking for usleep... yes
:info:configure checking for setenv... yes
:info:configure checking for unsetenv... yes
:info:configure checking for libiconv_open... yes
:info:configure checking for useable fallocate... no
:info:configure checking for FALLOC_FL_PUNCH_HOLE... no
:info:configure checking for FALLOC_FL_ZERO_RANGE... no
:info:configure checking for SYS_fallocate... no
:info:configure checking for getpgrp... yes
:info:configure checking for tcgetpgrp... yes
:info:configure checking whether getpgrp requires zero arguments... yes
:info:configure checking whether chown() modifies symlinks... no
:info:configure checking whether link() can hard-link symlinks... no
:info:configure checking whether link() can hard-link special files... yes
:info:configure checking for working socketpair... yes
:info:configure checking for getpass... yes
:info:configure checking for poptGetContext in -lpopt... yes
:info:configure checking whether to use included libpopt... no
:info:configure checking for unsigned char... yes
:info:configure checking for broken readdir... no
:info:configure checking for utimbuf... yes
:info:configure checking if gettimeofday takes tz argument... yes
:info:configure checking for C99 vsnprintf... yes
:info:configure checking for secure mkstemp... yes
:info:configure checking if mknod creates FIFOs... yes
:info:configure checking if mknod creates sockets... (-1 1) no
:info:configure checking whether -c -o works... yes
:info:configure checking for _acl... no
:info:configure checking for __acl... no
:info:configure checking for _facl... no
:info:configure checking for __facl... no
:info:configure checking whether to support ACLs... Using OS X ACLs
:info:configure checking whether to support extended attributes... Using OS X xattrs
:info:configure configure.sh: creating ./config.status
:info:configure config.status: creating Makefile
:info:configure config.status: creating lib/dummy
:info:configure config.status: creating zlib/dummy
:info:configure config.status: creating popt/dummy
:info:configure config.status: creating shconfig
:info:configure config.status: creating config.h
:info:configure     rsync 3.4.4 configuration successful
:debug:configure Executing portconfigure::configure_finish
:debug:configure Privilege de-escalation not attempted as not running as root.
:debug:build build phase started at 2026-07-12T01:48:08.780+0000 (Sun Jul 12 09:48:08 CST 2026)
:notice:build --->  Building rsync
:debug:build Executing org.macports.build (rsync)
:debug:build Environment: 
:debug:build CC_PRINT_OPTIONS='YES'
:debug:build CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/rsync-62cd6a74/work/.CC_PRINT_OPTIONS'
:debug:build CPATH='/opt/local/include'
:debug:build DEVELOPER_DIR='/Developer'
:debug:build LIBRARY_PATH='/opt/local/lib'
:debug:build MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:build SOURCE_DATE_EPOCH='1783820719'
:info:build Executing:  cd "/opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4" && /usr/bin/make -j2 -w all 
:debug:build system:  cd "/opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4" && /usr/bin/make -j2 -w all 
:info:build make: Entering directory `/opt/local/var/macports/build/rsync-62cd6a74/work/rsync-3.4.4'
:info:build awk -f ./daemon-parm.awk ./daemon-parm.txt
:info:build awk -f ./help-from-md.awk -v hfile=help-rsync.h ./rsync.1.md
:info:build awk -f ./help-from-md.awk -v hfile=help-rsyncd.h ./rsync.1.md
:info:build ./mkgitver
:info:build awk -f ./define-from-md.awk -v hfile=default-cvsignore.h ./rsync.1.md
:info:build awk -f ./define-from-md.awk -v hfile=default-dont-compress.h ./rsync.1.md
:info:build sed 's;\@bindir\@;/opt/local/bin;g' <./stunnel-rsyncd.conf.in >stunnel-rsyncd.conf
:info:build awk -f ./mkproto.awk ./*.c ./lib/compat.c daemon-parm.h
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c rsync.c -o rsync.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c generator.c -o generator.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c receiver.c -o receiver.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c cleanup.c -o cleanup.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c sender.c -o sender.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c exclude.c -o exclude.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c util1.c -o util1.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c util2.c -o util2.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c main.c -o main.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c checksum.c -o checksum.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c match.c -o match.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c syscall.c -o syscall.o
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -c android.c -o android.o
:info:build syscall.c: In function ‘do_lchown_at’:
:info:build syscall.c:535: error: too few arguments to function ‘do_lchown’
:info:build syscall.c: In function ‘do_chmod_at’:
:info:build syscall.c:1006: error: too few arguments to function ‘do_chmod’
:info:build syscall.c: In function ‘do_rename_at’:
:info:build syscall.c:1144: error: too few arguments to function ‘do_rename’
:info:build syscall.c: In function ‘do_xstat_at’:
:info:build syscall.c:1316: warning: unused parameter ‘at_flags’
:info:build syscall.c: In function ‘do_lstat_at’:
:info:build syscall.c:1367: error: ‘AT_SYMLINK_NOFOLLOW’ undeclared (first use in this function)
:info:build syscall.c:1367: error: (Each undeclared identifier is reported only once
:info:build syscall.c:1367: error: for each function it appears in.)
:info:build make: *** [syscall.o] Error 1
:info:build make: *** Waiting for unfinished jobs....
```

At least 3.4.1 is known to build and work fine.

**Comment by barracuda156** [comment]
@tridge Could you please have a look? A broken `rsync` will be really bad :)

**Comment by steadytao** [comment]
@barracuda156 

Thanks for the report. I traced this against the signed 3.4.4 source and the patch in macports/macports-ports#33538.

The failures have two causes:
- The `do_lchown`, `do_chmod` and `do_rename` argument errors come from MacPorts' updated `fileflags.diff`. It extends those functions and their `_at` wrappers with file-flags arguments but misses the no-`AT_FDCWD` fallback calls. Those need correcting in the MacPorts patch.
- The `AT_SYMLINK_NOFOLLOW` error is upstream. `do_lstat_at()` references it whenever `SUPPORT_LINKS` is enabled even when an older platform does not define it. That path should fall back to `do_lstat()` when the required `*at` support is unavailable.

The unused `at_flags` warning is from the same fallback configuration. I think this issue should remain open for the upstream `do_lstat_at()` portability fix while the argument-count failures are handled in macports/macports-ports#33538

**Comment by steadytao** [comment]
I will work on the upstream issue now, give me a few minutes.

**Comment by steadytao** [comment]
Testing took a lot longer then I thought 🤣 Pushing very shortly.

**Comment by barracuda156** [comment]
Great, thank you!

**Comment by barracuda156** [comment]
@steadytao On a side note, why does FreeBSD and MacPorts even need 1,5k LoC patch? https://github.com/freebsd/freebsd-ports/blob/e05695c847b90e2d4373c7f533a5872d61a8794f/net/rsync/files/extra-patch-file-flags.diff
If it is something useful, perhaps it can be upstreamed (but correctly, without breaking things)?

**Comment by steadytao** [comment]
> [@steadytao](https://github.com/steadytao) On a side note, why does FreeBSD and MacPorts even need 1,5k LoC patch?

My immediate thoughts are due to the fact that unfortunately some distros and porters simply fix issues with patchfiles rataher then telling us the issues exist *(I have no clue why)*. But I will have to take a bit of a deeper look in regards to that.

**Comment by steadytao** [comment]
My initial thoughts were a bit too broad. The large FreeBSD patch is mainly the optional `--file-flags` feature that originated in rsync’s own official patch bundle. The real issue is that substantial optional patches drift as upstream internals change while smaller compatibility, packaging and stable-backport patches are maintained separately by each distribution. I have decided to audit those categories before suggesting what should move upstream after our security release rolls out (3.5)

**Comment by tridge** [comment]
@barracuda156 should be fixed in master now, please test

**Comment by barracuda156** [comment]
@tridge Thank you, I will try today
