### ISSUE TITLE
rsync 3.4.3 and later won't build for Linux < 5.6 out of the box due to openat2()

### ISSUE THREAD

**Issue by mmayer** [WayneD/rsync#924]
While "configure" provides a command line option for disabling the use of openat2(), it doesn't try to detect on its own whether the target system supports the sys call. This means that just running ./configure && make against an older kernel will fail

```
gcc -I. -I. -I./popt -I./zlib -g -O2 -DHAVE_CONFIG_H -Wall -W  -c syscall.c -o syscall.o
syscall.c:38:10: fatal error: linux/openat2.h: No such file or directory
 #include <linux/openat2.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:72: recipe for target 'syscall.o' failed
make: *** [syscall.o] Error 1

```

This can be remedied by manually configuring rsync with "--disable-openat2", but I believe there is a better way. Ensuring SYS_openat2 is supported is a quick check that can be easily added to configure, making the experience automatic and seamless.

**Comment by mmayer** [comment]
PS: I am preparing a pull request with a proposed implementation.

**Comment by buhtz** [comment]
Duplicate of #905?

**Comment by mmayer** [comment]
Looks like a duplicate. But this one comes with a solution (pull request).

**Comment by timmc** [comment]
FYI, this issue was probably introduced in https://github.com/RsyncProject/rsync/commit/1d5b5ab83af84db0f66283d4cf5931d16e71f17e -- take a look at the commit authors.

**Comment by fda77** [comment]
No, see comment of @buhtz

**Comment by timmc** [comment]
Yeah, I saw your report. I guess it could have been one of several such vibe-coded commits.

**Comment by fda77** [comment]
Thanks for the warning! I didnt know rsync is flooded with ai slop. In changelog there is nothing about "claude", which did 76 commits since Mar 1 2026 (3 months)
Maybe i should switch back to 3.4.1 released Jan 15, 2025

**Comment by tridge** [comment]
this is fixed in master, I now have an ubuntu 20.04 box in my local set of test VMs to ensure it doesn't bitrot
