### ISSUE TITLE
error: pointer targets in passing argument 2 of ‘getgroups’ differ in signedness

### ISSUE THREAD

**Issue by barracuda156** [WayneD/rsync#338]
`rsync` 3.2.4 fails to build on 10.6.8 Rosetta for `ppc` with the following error:
```
uidlist.c: In function ‘is_in_group’:
uidlist.c:210: error: pointer targets in passing argument 2 of ‘getgroups’ differ in signedness
uidlist.c:213: warning: comparison between signed and unsigned
uidlist.c:232: warning: comparison between signed and unsigned
make: *** [uidlist.o] Error 1
```
The error is consistent (two different installations, same error) and happens only on 10.6.8 Rosetta: neither 10.5.8 nor 10.6 PPC are affected. Previous version of `rsync` built fine on Rosetta too.
More info and logs here: https://trac.macports.org/ticket/65034

**Comment by WayneD** [comment]
Configure sets GROUPLIST_T to what it thinks is the right choice between gid_t or int.  Apparently it got it wrong for your system. You can get a normal build by tweaking config.h to fix the define to be `#define GETGROUPS_T gid_t`.  However, we also need to figure out why configure messed up.

I'm attaching something similar to what configure would have run, so if you could compile it with something like:

```
gcc -g -O2 -Wall -W -pedantic-errors -o chk chk-grouplist.c
```

If that compiles fine, what does running `./chk` output?  It should say something like:

```
n=12
4294967295 vs 4294967295
```

[chk-grouplist.c.txt](https://github.com/WayneD/rsync/files/9235105/chk-grouplist.c.txt)

**Comment by WayneD** [comment]
I just saw that this is apparently a cross-compile situation.  The configure code should probably just be modified to assume that GETGROUPS_T is gid_t when cross compiling, as the code can't check the target system.  Note that older rsync versions didn't fail to compile only because `-pedantic-errors` wasn't in effect in earlier versions, so such a type mismatch was probably just warned about but (scarily) nobody noticed.

**Comment by WayneD** [comment]
I tweaked configure.ac to default to git_t when cross-compiling (since the check program can't be run).  This should fix things for your build that is failing, and will be available in the soon-to-be-released 3.2.5.

If someone is cross-compiling and needs a different GETGROUPS_T value, they should manually tweak config.h after the configure run, such as:

```
sed -i 's/^#define GETGROUPS_T.*/#define GETGROUPS_T int/' config.h
```

**Comment by barracuda156** [comment]
@WayneD Thank you for responding. This is not a cross-compilation case, Rosetta runs `ppc32` binaries natively. So while the physical CPU is Intel, `--build` = `--host` = `--target` = `powerpc-apple-darwin10`.

**Comment by WayneD** [comment]
Specifying `--host` triggers cross-compiling in configure.

**Comment by barracuda156** [comment]
@WayneD Usually I only set `--build=powerpc-apple-darwin10` for Rosetta cases, whenever that is needed to do manually.

I will try you suggestion above and report back if it works. Thank you.

**Comment by WayneD** [comment]
If you need to go with a sed override, your case would need to manually force git_t instead of the int of the example.  (Just in case that wasn't obvious...)

**Comment by barracuda156** [comment]
@WayneD I went with sed, adding the following to portfile:
```
platform darwin 10 powerpc {
    post-configure {
        reinplace "s|#define GETGROUPS_T int|#define GETGROUPS_T gid_t|" ${worksrcpath}/config.h
    }
}
```
And it worked! Thank you.
```
10:svacchanda$ port -v installed | grep rsync
  rsync @3.2.3_1 requested_variants='' platform='darwin 10' archs='ppc' date='2022-07-17T00:35:15+0545'
  rsync @3.2.4_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-08-04T21:50:27+0545'
```
